set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT_10M]
set_property IOSTANDARD LVCMOS33 [get_ports CLRN]
set_property PACKAGE_PIN P17 [get_ports CLK]
set_property PACKAGE_PIN R11 [get_ports CLRN]
set_property PACKAGE_PIN L18 [get_ports CLK_OUT_10M]
