webtalk_init -webtalk_dir C:/Users/Dadingdang/Xilinx Project/ES_design/ES_design.sim/sim_1/behav/xsim/xsim.dir/fp_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct 27 16:22:56 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "212196e4-e0a5-41dd-8150-db89ab212223" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f40dafe96c604580b5b5e2d9b7d07378" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "140" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5800H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "68.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2503345 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "11.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "25968_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1019421533 -regid "" -xml C:/Users/Dadingdang/Xilinx Project/ES_design/ES_design.sim/sim_1/behav/xsim/xsim.dir/fp_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Dadingdang/Xilinx Project/ES_design/ES_design.sim/sim_1/behav/xsim/xsim.dir/fp_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Dadingdang/Xilinx Project/ES_design/ES_design.sim/sim_1/behav/xsim/xsim.dir/fp_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
