# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Dadingdang/Xilinx Project/ES_design/ES_design.srcs/sources_1/ip/blk_sin/blk_sin.xci
# IP: The module: 'blk_sin' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dadingdang/Xilinx Project/ES_design/ES_design.srcs/sources_1/ip/blk_sin/blk_sin_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_sin'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Dadingdang/Xilinx Project/ES_design/ES_design.srcs/sources_1/ip/blk_sin/blk_sin.xci
# IP: The module: 'blk_sin' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dadingdang/Xilinx Project/ES_design/ES_design.srcs/sources_1/ip/blk_sin/blk_sin_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_sin'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
